CREATE TABLE IF NOT EXISTS videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bvid TEXT NOT NULL UNIQUE,
  aid BIGINT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  owner_mid BIGINT,
  owner_name TEXT,
  owner_dir_name TEXT,
  work_dir_name TEXT,
  source_type TEXT NOT NULL DEFAULT 'bili',
  publish_enabled INTEGER NOT NULL DEFAULT 1,
  page_count INTEGER NOT NULL DEFAULT 0,
  root_comment_rpid BIGINT,
  top_comment_rpid BIGINT,
  preserved_top_comment_rpid BIGINT,
  publish_needs_rebuild INTEGER NOT NULL DEFAULT 0,
  publish_rebuild_reason TEXT,
  last_scan_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS video_parts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT NOT NULL REFERENCES videos(id) ON DELETE CASCADE,
  page_no INTEGER NOT NULL,
  cid BIGINT NOT NULL,
  part_title TEXT NOT NULL,
  duration_sec INTEGER NOT NULL DEFAULT 0,
  subtitle_path TEXT,
  subtitle_source TEXT,
  subtitle_lang TEXT,
  source_path TEXT,
  subtitle_text TEXT,
  prompt_text TEXT,
  summary_text TEXT,
  summary_text_processed TEXT,
  summary_hash TEXT,
  published INTEGER NOT NULL DEFAULT 0,
  published_comment_rpid BIGINT,
  published_at TEXT,
  is_deleted INTEGER NOT NULL DEFAULT 0,
  deleted_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (video_id, cid)
);

CREATE INDEX IF NOT EXISTS idx_video_parts_video_id
  ON video_parts(video_id);
CREATE INDEX IF NOT EXISTS idx_video_parts_video_page
  ON video_parts(video_id, page_no);

CREATE TABLE IF NOT EXISTS pipeline_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id TEXT,
  video_id BIGINT REFERENCES videos(id) ON DELETE CASCADE,
  bvid TEXT,
  video_title TEXT,
  page_no INTEGER,
  cid BIGINT,
  part_title TEXT,
  scope TEXT NOT NULL,
  action TEXT NOT NULL,
  status TEXT NOT NULL,
  message TEXT,
  details_json TEXT,
  created_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pipeline_events_created_at
  ON pipeline_events(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_events_bvid_created_at
  ON pipeline_events(bvid, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_events_run_id
  ON pipeline_events(run_id, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS pipeline_runs (
  run_id TEXT PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
  bvid TEXT,
  video_title TEXT,
  trigger_source TEXT,
  status TEXT NOT NULL,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_bvid_updated_at
  ON pipeline_runs(bvid, updated_at DESC, run_id DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status_updated_at
  ON pipeline_runs(status, updated_at DESC, run_id DESC);

CREATE TABLE IF NOT EXISTS pipeline_run_state (
  run_id TEXT PRIMARY KEY REFERENCES pipeline_runs(run_id) ON DELETE CASCADE,
  latest_event_id BIGINT NOT NULL REFERENCES pipeline_events(id) ON DELETE CASCADE,
  video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
  bvid TEXT,
  video_title TEXT,
  trigger_source TEXT,
  run_status TEXT NOT NULL,
  current_scope TEXT,
  current_action TEXT,
  current_status TEXT,
  current_stage TEXT,
  current_page_no INTEGER,
  current_cid BIGINT,
  current_part_title TEXT,
  last_message TEXT,
  last_error_message TEXT,
  failed_scope TEXT,
  failed_action TEXT,
  failed_step TEXT,
  log_path TEXT,
  summary_path TEXT,
  pending_summary_path TEXT,
  started_at TEXT NOT NULL,
  finished_at TEXT,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_pipeline_run_state_bvid_updated_at
  ON pipeline_run_state(bvid, updated_at DESC, latest_event_id DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_run_state_run_status_updated_at
  ON pipeline_run_state(run_status, updated_at DESC, latest_event_id DESC);

CREATE TABLE IF NOT EXISTS gap_notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gap_key TEXT NOT NULL UNIQUE,
  bvid TEXT NOT NULL,
  video_title TEXT,
  from_page_no INTEGER NOT NULL,
  from_cid BIGINT NOT NULL,
  to_page_no INTEGER NOT NULL,
  to_cid BIGINT NOT NULL,
  gap_start_at TEXT NOT NULL,
  gap_end_at TEXT NOT NULL,
  gap_seconds INTEGER NOT NULL,
  notified_at TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_gap_notifications_bvid_notified_at
  ON gap_notifications(bvid, notified_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS recent_reprocess_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  video_id BIGINT REFERENCES videos(id) ON DELETE SET NULL,
  bvid TEXT NOT NULL,
  video_title TEXT,
  candidate_key TEXT NOT NULL,
  reasons_json TEXT NOT NULL,
  paste_pages_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL,
  error_message TEXT,
  details_json TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  finished_at TEXT
);

CREATE INDEX IF NOT EXISTS idx_recent_reprocess_runs_candidate_status
  ON recent_reprocess_runs(candidate_key, status, finished_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_recent_reprocess_runs_bvid_created_at
  ON recent_reprocess_runs(bvid, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS app_settings (
  setting_key TEXT PRIMARY KEY,
  value_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS scheduler_status (
  scheduler_key TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  mode TEXT,
  timezone TEXT,
  pid INTEGER,
  hostname TEXT,
  summary_users TEXT,
  summary_concurrency INTEGER,
  current_tasks_json TEXT,
  last_summary_at TEXT,
  last_publish_at TEXT,
  last_gap_check_at TEXT,
  last_retry_failures_at TEXT,
  last_zombie_recovery_at TEXT,
  last_refresh_at TEXT,
  last_cleanup_at TEXT,
  last_error TEXT,
  started_at TEXT,
  last_heartbeat_at TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS operation_audits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  scope TEXT NOT NULL,
  trigger_source TEXT NOT NULL,
  bvid TEXT,
  run_id TEXT,
  request_json TEXT,
  status TEXT NOT NULL,
  result_json TEXT,
  error_message TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_operation_audits_bvid_created_at
  ON operation_audits(bvid, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_operation_audits_created_at
  ON operation_audits(created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_operation_audits_status_created_at
  ON operation_audits(status, created_at DESC, id DESC);
