import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const videos = sqliteTable("videos", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  bvid: text("bvid").notNull(),
  aid: integer("aid").notNull(),
  title: text("title").notNull(),
  owner_mid: integer("owner_mid"),
  owner_name: text("owner_name"),
  owner_dir_name: text("owner_dir_name"),
  work_dir_name: text("work_dir_name"),
  page_count: integer("page_count").notNull(),
  root_comment_rpid: integer("root_comment_rpid"),
  top_comment_rpid: integer("top_comment_rpid"),
  publish_needs_rebuild: integer("publish_needs_rebuild").notNull(),
  publish_rebuild_reason: text("publish_rebuild_reason"),
  last_scan_at: text("last_scan_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  bvidUnique: uniqueIndex("videos_bvid_unique").on(table.bvid),
  aidUnique: uniqueIndex("videos_aid_unique").on(table.aid),
}));

export const videoParts = sqliteTable("video_parts", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  video_id: integer("video_id").notNull().references(() => videos.id, { onDelete: "cascade" }),
  page_no: integer("page_no").notNull(),
  cid: integer("cid").notNull(),
  part_title: text("part_title").notNull(),
  duration_sec: integer("duration_sec").notNull(),
  subtitle_path: text("subtitle_path"),
  subtitle_source: text("subtitle_source"),
  subtitle_lang: text("subtitle_lang"),
  summary_text: text("summary_text"),
  summary_text_processed: text("summary_text_processed"),
  summary_hash: text("summary_hash"),
  published: integer("published").notNull(),
  published_comment_rpid: integer("published_comment_rpid"),
  published_at: text("published_at"),
  is_deleted: integer("is_deleted").notNull(),
  deleted_at: text("deleted_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  videoIdIdx: index("idx_video_parts_video_id").on(table.video_id),
  videoPageIdx: index("idx_video_parts_video_page").on(table.video_id, table.page_no),
  videoCidUnique: uniqueIndex("idx_video_parts_video_cid").on(table.video_id, table.cid),
}));

export const pipelineEvents = sqliteTable("pipeline_events", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  run_id: text("run_id"),
  video_id: integer("video_id").references(() => videos.id, { onDelete: "cascade" }),
  bvid: text("bvid"),
  video_title: text("video_title"),
  page_no: integer("page_no"),
  cid: integer("cid"),
  part_title: text("part_title"),
  scope: text("scope").notNull(),
  action: text("action").notNull(),
  status: text("status").notNull(),
  message: text("message"),
  details_json: text("details_json"),
  created_at: text("created_at").notNull(),
}, (table) => ({
  createdAtIdx: index("idx_pipeline_events_created_at").on(table.created_at, table.id),
  bvidCreatedAtIdx: index("idx_pipeline_events_bvid_created_at").on(table.bvid, table.created_at, table.id),
  runIdIdx: index("idx_pipeline_events_run_id").on(table.run_id, table.created_at, table.id),
}));

export const pipelineRuns = sqliteTable("pipeline_runs", {
  run_id: text("run_id").primaryKey(),
  video_id: integer("video_id").references(() => videos.id, { onDelete: "set null" }),
  bvid: text("bvid"),
  video_title: text("video_title"),
  trigger_source: text("trigger_source"),
  status: text("status").notNull(),
  started_at: text("started_at").notNull(),
  finished_at: text("finished_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  statusUpdatedAtIdx: index("idx_pipeline_runs_status_updated_at").on(table.status, table.updated_at, table.run_id),
  bvidUpdatedAtIdx: index("idx_pipeline_runs_bvid_updated_at").on(table.bvid, table.updated_at, table.run_id),
}));

export const pipelineRunState = sqliteTable("pipeline_run_state", {
  run_id: text("run_id").primaryKey().references(() => pipelineRuns.run_id, { onDelete: "cascade" }),
  latest_event_id: integer("latest_event_id").notNull().references(() => pipelineEvents.id, { onDelete: "cascade" }),
  video_id: integer("video_id").references(() => videos.id, { onDelete: "set null" }),
  bvid: text("bvid"),
  video_title: text("video_title"),
  trigger_source: text("trigger_source"),
  run_status: text("run_status").notNull(),
  current_scope: text("current_scope"),
  current_action: text("current_action"),
  current_status: text("current_status"),
  current_stage: text("current_stage"),
  current_page_no: integer("current_page_no"),
  current_cid: integer("current_cid"),
  current_part_title: text("current_part_title"),
  last_message: text("last_message"),
  last_error_message: text("last_error_message"),
  failed_scope: text("failed_scope"),
  failed_action: text("failed_action"),
  failed_step: text("failed_step"),
  log_path: text("log_path"),
  summary_path: text("summary_path"),
  pending_summary_path: text("pending_summary_path"),
  started_at: text("started_at").notNull(),
  finished_at: text("finished_at"),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  bvidUpdatedAtIdx: index("idx_pipeline_run_state_bvid_updated_at").on(table.bvid, table.updated_at, table.latest_event_id),
  statusUpdatedAtIdx: index("idx_pipeline_run_state_run_status_updated_at").on(table.run_status, table.updated_at, table.latest_event_id),
}));

export const operationAudits = sqliteTable("operation_audits", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  action: text("action").notNull(),
  scope: text("scope").notNull(),
  trigger_source: text("trigger_source").notNull(),
  bvid: text("bvid"),
  run_id: text("run_id"),
  request_json: text("request_json"),
  status: text("status").notNull(),
  result_json: text("result_json"),
  error_message: text("error_message"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  createdAtIdx: index("idx_operation_audits_created_at").on(table.created_at, table.id),
  bvidCreatedAtIdx: index("idx_operation_audits_bvid_created_at").on(table.bvid, table.created_at, table.id),
  statusCreatedAtIdx: index("idx_operation_audits_status_created_at").on(table.status, table.created_at, table.id),
}));

export const schedulerStatus = sqliteTable("scheduler_status", {
  scheduler_key: text("scheduler_key").primaryKey(),
  status: text("status").notNull(),
  mode: text("mode"),
  timezone: text("timezone"),
  pid: integer("pid"),
  hostname: text("hostname"),
  summary_users: text("summary_users"),
  summary_concurrency: integer("summary_concurrency"),
  current_tasks_json: text("current_tasks_json"),
  last_summary_at: text("last_summary_at"),
  last_publish_at: text("last_publish_at"),
  last_gap_check_at: text("last_gap_check_at"),
  last_retry_failures_at: text("last_retry_failures_at"),
  last_zombie_recovery_at: text("last_zombie_recovery_at"),
  last_refresh_at: text("last_refresh_at"),
  last_cleanup_at: text("last_cleanup_at"),
  last_error: text("last_error"),
  started_at: text("started_at"),
  last_heartbeat_at: text("last_heartbeat_at"),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const gapNotifications = sqliteTable("gap_notifications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  gap_key: text("gap_key").notNull(),
  bvid: text("bvid").notNull(),
  video_title: text("video_title"),
  from_page_no: integer("from_page_no").notNull(),
  from_cid: integer("from_cid").notNull(),
  to_page_no: integer("to_page_no").notNull(),
  to_cid: integer("to_cid").notNull(),
  gap_start_at: text("gap_start_at").notNull(),
  gap_end_at: text("gap_end_at").notNull(),
  gap_seconds: integer("gap_seconds").notNull(),
  notified_at: text("notified_at").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
}, (table) => ({
  gapKeyUnique: uniqueIndex("idx_gap_notifications_gap_key").on(table.gap_key),
  bvidNotifiedAtIdx: index("idx_gap_notifications_bvid_notified_at").on(table.bvid, table.notified_at, table.id),
}));

export const appSettings = sqliteTable("app_settings", {
  setting_key: text("setting_key").primaryKey(),
  value_json: text("value_json").notNull(),
  created_at: text("created_at").notNull(),
  updated_at: text("updated_at").notNull(),
});

export const schema = {
  appSettings,
  gapNotifications,
  operationAudits,
  pipelineEvents,
  pipelineRunState,
  pipelineRuns,
  schedulerStatus,
  videoParts,
  videos,
};
